server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false